apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-o8uy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0038-tenant/tkrw-pr712-0075-0038-app/devfile-sample-o8uy@sha256:ac12e572f0c375b7070e0b62f0d97cf158d83e3ce0313d42d432fdb78e38bdf5
        name: my-nodejs
        resources: {}
status: {}
